# Generated by Django 5.1 on 2024-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_rename_updated_at_messageinfo_dealt_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='cli_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
