# Generated by Django 5.1 on 2024-10-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'category', 'size', 'thickness', 'colour')},
        ),
    ]
