# Generated by Django 5.1 on 2024-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='about_us')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
